### ISSUE TITLE
Crash on Android 12.

### ISSUE THREAD

**Issue by MagneFire** [AsteroidOS/AsteroidOSSync#149]
Just updated my phone to Android 12 (Samsung OneUI 4) after the update the app appears to be crashing.
When I find the time, I shall debug this further, for now here's the `logcat`
```
01-10 19:09:45.511 26869 26869 D class org.asteroidos.sync.services.SynchronizationService: BLE Service registered: 00008071-0000-0000-0000-00a57e401d05
01-10 19:09:45.512 26869 26869 D class org.asteroidos.sync.services.SynchronizationService: BLE Service registered: 00006071-0000-0000-0000-00a57e401d05
01-10 19:09:45.512 26869 26869 D class org.asteroidos.sync.services.SynchronizationService: BLE Service registered: 00005071-0000-0000-0000-00a57e401d05
01-10 19:09:45.513 26869 26869 I BluetoothDevice: createBondOutOfBand() for device 4343A0_C called by pid: 26869 tid: 26869
01-10 19:09:45.516 26869 26869 D AndroidRuntime: Shutting down VM
01-10 19:09:45.517 26869 26869 E AndroidRuntime: FATAL EXCEPTION: main
01-10 19:09:45.517 26869 26869 E AndroidRuntime: Process: org.asteroidos.sync, PID: 26869
01-10 19:09:45.517 26869 26869 E AndroidRuntime: java.lang.RuntimeException: Unable to create service org.asteroidos.sync.services.SynchronizationService: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10801, packageName = org.asteroidos.sync, attributionTag = null, token = android.os.BinderProxy@8c9a3c5, next = null }: AdapterService createBond
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4949)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.app.ActivityThread.access$1900(ActivityThread.java:310)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8633)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
01-10 19:09:45.517 26869 26869 E AndroidRuntime: Caused by: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10801, packageName = org.asteroidos.sync, attributionTag = null, token = android.os.BinderProxy@8c9a3c5, next = null }: AdapterService createBond
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2421)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2404)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2346)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.bluetooth.IBluetooth$Stub$Proxy.createBond(IBluetooth.java:5162)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.bluetooth.BluetoothDevice.createBondInternal(BluetoothDevice.java:2341)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.bluetooth.BluetoothDevice.createBond(BluetoothDevice.java:2275)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.bluetooth.BluetoothDevice.createBond(BluetoothDevice.java:2252)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at org.asteroidos.sync.services.SynchronizationService.handleConnect(SynchronizationService.java:101)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at org.asteroidos.sync.services.SynchronizationService.onCreate(SynchronizationService.java:275)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4936)
01-10 19:09:45.517 26869 26869 E AndroidRuntime:        ... 9 more
```

Edit:
This can be easily solved by manually giving permission to the `Nearby devices` permission.

**Comment by jrtberlin** [comment]
Does it work when you add the `android.permission.BLUETOOTH_CONNECT` permission to the manifest?

**Comment by MagneFire** [comment]
It appears to be already in the manifest: https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/AndroidManifest.xml#L8

**Comment by jrtberlin** [comment]
I think we need to check and request the permission on startup.

**Comment by MagneFire** [comment]
Yup, that's indeed it. Maybe we can now also get rid of the location permission?

**Comment by jrtberlin** [comment]
We can only on Android >= 12.
