### ISSUE TITLE
Asteroid 0.21 crash on LineageOS 17.1

### ISSUE THREAD

**Issue by comradekingu** [AsteroidOS/AsteroidOSSync#153]
Crashes on startup after granting permissions.
Same for 0.20 and 0.19.

LineageOS 17.1 (Android 10) on motog7. Works on LO 18 on a different phone, and 15.1 (Android 8.1.0) on a different phone.

<details>
FATAL EXCEPTION: Thread-2
Process: org.asteroidos.sync, PID: 3043
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
	at org.asteroidos.sync.utils.AppInfoHelper.getPackageInfo(AppInfoHelper.java:56)
	at org.asteroidos.sync.MainActivity$3.run(MainActivity.java:109)
	at java.lang.Thread.run(Thread.java:919)
</details>

**Comment by jrtberlin** [comment]
This happens in a [function](https://github.com/AsteroidOS/AsteroidOSSync/blob/1418f671580f57acf273297a311d739510fa5927/app/src/main/java/org/asteroidos/sync/utils/AppInfoHelper.java#L56) where App icons get collected for the notification system.
Do you have an app without icon on the device? Maybe a system app?

**Comment by comradekingu** [comment]
Like Magisk?

**Comment by jrtberlin** [comment]
Could be. I think the best solution is to handle missing or broken icons by adding a fallback icon.

**Comment by jrtberlin** [comment]
Does this still happen on [0.22](https://f-droid.org/repo/org.asteroidos.sync_22.apk)?

**Comment by comradekingu** [comment]
@jrtberlin Yes.

**Comment by comradekingu** [comment]
I got this trying to open "Zim Launcher"

Build version: 0.6.2b 
Build date: 1979-11-30 01:00:00 
Current date: 2022-03-11 19:03:59 
Device: Motorola moto g(7) power 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
	at com.android.launcher3.graphics.ColorExtractor.findDominantColorByHue(ColorExtractor.java:51)
	at com.android.launcher3.graphics.ColorExtractor.findDominantColorByHue(ColorExtractor.java:41)
	at org.zimmob.zimlx.iconpack.DefaultPack.extractColor(DefaultPack.kt:260)
	at org.zimmob.zimlx.iconpack.DefaultPack.wrapToAdaptiveIcon(DefaultPack.kt:251)
	at org.zimmob.zimlx.iconpack.DefaultPack.getIcon(DefaultPack.kt:131)
	at org.zimmob.zimlx.iconpack.IconPackManager.getIcon(IconPackManager.kt:110)
	at org.zimmob.zimlx.iconpack.ZimIconProvider.getIcon(ZimIconProvider.kt:32)
	at com.android.launcher3.IconCache.getFullResIcon(IconCache.java:192)
	at com.android.launcher3.IconCache.getFullResIcon(IconCache.java:188)
	at com.android.launcher3.IconCache.cacheLocked(IconCache.java:559)
	at com.android.launcher3.IconCache.getTitleAndIcon(IconCache.java:501)
	at com.android.launcher3.IconCache.getTitleAndIcon(IconCache.java:473)
	at com.android.launcher3.AllAppsList.add(AllAppsList.java:84)
	at com.android.launcher3.model.LoaderTask.loadAllApps(LoaderTask.java:843)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:187)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by moWerk** [comment]
We advise to use GB at this point sine AsteroidOSSync is unmaintained.
