### ISSUE TITLE
App crashing on LineageOS with MicroG

### ISSUE THREAD

**Issue by 5KRC1** [AsteroidOS/AsteroidOSSync#182]
AsteroidOSSync crashes upon connecting with LG Watch Urbane.
I use Google Pixel 4a with LineageOS 18.1 and MicroG.
Here are the logs of the error:
```
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime	FATAL EXCEPTION: main
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime	Process: org.asteroidos.sync, PID: 24452
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime	java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGattCharacteristic.setService(android.bluetooth.BluetoothGattService)' on a null object reference
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at android.bluetooth.BluetoothGattService.addCharacteristic(BluetoothGattService.java:246)
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at org.asteroidos.sync.asteroid.AsteroidBleManager$AsteroidBleManagerGattCallback.isRequiredServiceSupported(AsteroidBleManager.java:116)
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at no.nordicsemi.android.ble.BleManagerHandler$3.onServicesDiscovered(BleManagerHandler.java:1977)
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at android.bluetooth.BluetoothGatt$1$5.run(BluetoothGatt.java:338)
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at android.os.Handler.handleCallback(Handler.java:938)
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at android.os.Handler.dispatchMessage(Handler.java:99)
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at android.os.Looper.loop(Looper.java:223)
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at android.app.ActivityThread.main(ActivityThread.java:7664)
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at java.lang.reflect.Method.invoke(Native Method)
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-17 16:32:25.375	24452	24452	org.asteroidos.sync	E	AndroidRuntime		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-17 16:32:25.386	24452	24452	org.asteroidos.sync	I	Process	Sending signal. PID: 24452 SIG: 9
```
Thanks in advance. :)

**Comment by 5KRC1** [comment]
Never mind, it was the issue with my watch, since I had already previously paired with it on my phone.
Therefore the solution was to just forget the device on my phone and  reconnect with it.
