### ISSUE TITLE
Crash on start in SDK 19

### ISSUE THREAD

**Issue by neochapay** [AsteroidOS/AsteroidOSSync#2]
If i build app on minSdk 19 i have crash 

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.asteroidos.sync, PID: 25870
                  java.lang.NoClassDefFoundError: org.asteroidos.sync.ble.MediaService
                      at org.asteroidos.sync.services.SynchronizationService$SynchronizationHandler.handleMessage(SynchronizationService.java:99)
                      at android.os.Handler.dispatchMessage(Handler.java:110)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:5299)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                      at dalvik.system.NativeStart.main(Native Method)`

**Comment by FlorentRevest** [comment]
AsteroidOSSync uses quite "recent" BLE API and minSdk 21 has been chosen for a reason. This crash shouldn't be an open issue and hasn't been a problem for anyone else so I close the bug report.
