### ISSUE TITLE
Weather-related crash on establishing watch connection

### ISSUE THREAD

**Issue by TheLastProject** [AsteroidOS/AsteroidOSSync#3]
Phone: Motorola Moto E 2015 LTE
Phone OS: CyanogenMod 14.1-20161216-NIGHTLY-surnia (Android 7.1.1)
Watch: LG G Watch (dory) running the official AsteroidOS alpha 1.0 build

How to reproduce:
1. Start AsteroidOS Sync app
2. Scan for watches
3. Click dory
4. Wait for the state to switch to Connected

Expected result:
The watch stays connected and everything works without issue.

Actual result:
AsteroidOS Sync instantly crashes with the following log (I have hidden the app ID to make it less easy to scrape for bots and the uuid for my privacy):
```
12-17 15:26:07.700 10131 10162 D OkHttp  : --> GET http://api.openweathermap.org/data/2.5/forecast?appid=<hidden>&q=NewYork http/1.1
12-17 15:26:07.700 10131 10162 D OkHttp  : --> END GET
12-17 15:26:07.709 10131 10131 D BluetoothManager: getConnectionState()
12-17 15:26:07.709 10131 10131 D BluetoothManager: getConnectedDevices
12-17 15:26:07.714 10131 10131 D BluetoothGatt: setCharacteristicNotification() - uuid: <hidden> enable: true
12-17 15:26:07.754 10131 10162 D OkHttp  : <-- 200 OK http://api.openweathermap.org/data/2.5/forecast?appid=<hidden>&q=NewYork (53ms)
12-17 15:26:07.754 10131 10162 D OkHttp  : Server: openresty
12-17 15:26:07.754 10131 10162 D OkHttp  : Date: Sat, 17 Dec 2016 14:26:07 GMT
12-17 15:26:07.754 10131 10162 D OkHttp  : Content-Type: application/json; charset=utf-8
12-17 15:26:07.754 10131 10162 D OkHttp  : Transfer-Encoding: chunked
12-17 15:26:07.754 10131 10162 D OkHttp  : Connection: keep-alive
12-17 15:26:07.754 10131 10162 D OkHttp  : X-Cache-Key: /data/2.5/forecast?q=newyork
12-17 15:26:07.754 10131 10162 D OkHttp  : Access-Control-Allow-Origin: *
12-17 15:26:07.754 10131 10162 D OkHttp  : Access-Control-Allow-Credentials: true
12-17 15:26:07.754 10131 10162 D OkHttp  : Access-Control-Allow-Methods: GET, POST
12-17 15:26:07.754 10131 10162 D OkHttp  : OkHttp-Sent-Millis: 1481984767728
12-17 15:26:07.755 10131 10162 D OkHttp  : OkHttp-Received-Millis: 1481984767752
12-17 15:26:07.761 10131 10162 D OkHttp  : {"city":{"id":5128581,"name":"New York","coord":{"lon":-74.005966,"lat":40.714272},"country":"US","population":0,"sys":{"population":0}},"c
od":"200","message":0.0209,"cnt":27,"list":[{"dt":1481986800,"main":{"temp":272.1,"temp_min":272.1,"temp_max":274.318,"pressure":1028.82,"sea_level":1032.36,"grnd_level":1028.82,"hum
idity":100,"temp_kf":-2.22},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],"clouds":{"all":92},"wind":{"speed":4.43,"deg":216.502},"rain":{"3h":0.05},"s
now":{"3h":3.7875},"sys":{"pod":"d"},"dt_txt":"2016-12-17 15:00:00"},{"dt":1481997600,"main":{"temp":273.91,"temp_min":273.91,"temp_max":275.578,"pressure":1024.33,"sea_level":1027.8
,"grnd_level":1024.33,"humidity":100,"temp_kf":-1.67},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],"clouds":{"all":92},"wind":{"speed":2.58,"deg":220.
5},"rain":{"3h":2.67},"snow":{"3h":1.6025},"sys":{"pod":"d"},"dt_txt":"2016-12-17 18:00:00"},{"dt":1482008400,"main":{"temp":274.72,"temp_min":274.72,"temp_max":275.834,"pressure":10
22.84,"sea_level":1026.44,"grnd_level":1022.84,"humidity":100,"temp_kf":-1.11},"weather":[{"id":501,"main":"Rain","description":"moderate rain","icon":"10d"}],"clouds":{"all":92},"wi
nd":{"speed":2.52,"deg":229.505},"rain":{"3h":3.43},"snow":{},"sys":{"pod":"d"},"dt_txt":"2016-12-17 21:00:00"},{"dt":1482019200,"main":{"temp":275.21,"temp_min":275.21,"temp_max":27
5.763,"pressure":1022.36,"sea_level":1025.88,"grnd_level":1022.36,"humidity":100,"temp_kf":-0.56},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10n"}],"clouds
":{"all":92},"wind":{"speed":1.82,"deg":207.503},"rain":{"3h":0.4},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-18 00:00:00"},{"dt":1482030000,"main":{"temp":278.275,"temp_min":278.
275,"temp_max":278.275,"pressure":1020.43,"sea_level":1023.96,"grnd_level":1020.43,"humidity":98,"temp_kf":0},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10
n"}],"clouds":{"all":88},"wind":{"speed":3.31,"deg":199.502},"rain":{"3h":0.1},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-18 03:00:00"},{"dt":1482040800,"main":{"temp":281.632,"te
mp_min":281.632,"temp_max":281.632,"pressure":1018.25,"sea_level":1021.76,"grnd_level":1018.25,"humidity":94,"temp_kf":0},"weather":[{"id":500,"main":"Rain","description":"light rain
","icon":"10n"}],"clouds":{"all":92},"wind":{"speed":4.66,"deg":210},"rain":{"3h":0.25},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-18 06:00:00"},{"dt":1482051600,"main":{"temp":28
3.605,"temp_min":283.605,"temp_max":283.605,"pressure":1016.56,"sea_level":1020,"grnd_level":1016.56,"humidity":92,"temp_kf":0},"weather":[{"id":500,"main":"Rain","description":"ligh
t rain","icon":"10n"}],"clouds":{"all":92},"wind":{"speed":5.67,"deg":214.505},"rain":{"3h":0.59},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-18 09:00:00"},{"dt":1482062400,"main":
{"temp":286.175,"temp_min":286.175,"temp_max":286.175,"pressure":1015.49,"sea_level":1018.91,"grnd_level":1015.49,"humidity":89,"temp_kf":0},"weather":[{"id":500,"main":"Rain","descr
iption":"light rain","icon":"10n"}],"clouds":{"all":100},"wind":{"speed":6.57,"deg":217.001},"rain":{"3h":0.35},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-18 12:00:00"},{"dt":1482
073200,"main":{"temp":287.366,"temp_min":287.366,"temp_max":287.366,"pressure":1016.63,"sea_level":1020.04,"grnd_level":1016.63,"humidity":90,"temp_kf":0},"weather":[{"id":500,"main"
:"Rain","description":"light rain","icon":"10d"}],"clouds":{"all":92},"wind":{"speed":6.91,"deg":223.505},"rain":{"3h":0.69},"snow":{},"sys":{"pod":"d"},"dt_txt":"2016-12-18 15:00:00
"},{"dt":1482084000,"main":{"temp":287.055,"temp_min":287.055,"temp_max":287.055,"pressure":1018.94,"sea_level":1022.32,"grnd_level":1018.94,"humidity":89,"temp_kf":0},"weather":[{"i
d":500,"main":"Rain","description":"light rain","icon":"10d"}],"clouds":{"all":92},"wind":{"speed":5.45,"deg":249.502},"rain":{"3h":0.72},"snow":{},"sys":{"pod":"d"},"dt_txt":"2016-1
2-18 18:00:00"},{"dt":1482094800,"main"
12-17 15:26:07.761 10131 10162 D OkHttp  : :{"temp":282.446,"temp_min":282.446,"temp_max":282.446,"pressure":1023.58,"sea_level":1027.02,"grnd_level":1023.58,"humidity":97,"temp_kf":
0},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],"clouds":{"all":92},"wind":{"speed":5.44,"deg":279.5},"rain":{"3h":2.93},"snow":{},"sys":{"pod":"d"},"
dt_txt":"2016-12-18 21:00:00"},{"dt":1482105600,"main":{"temp":279.553,"temp_min":279.553,"temp_max":279.553,"pressure":1029.88,"sea_level":1033.4,"grnd_level":1029.88,"humidity":97,
"temp_kf":0},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10n"}],"clouds":{"all":92},"wind":{"speed":5.11,"deg":327.507},"rain":{"3h":0.52},"snow":{},"sys":{
"pod":"n"},"dt_txt":"2016-12-19 00:00:00"},{"dt":1482116400,"main":{"temp":275.766,"temp_min":275.766,"temp_max":275.766,"pressure":1035.07,"sea_level":1038.65,"grnd_level":1035.07,"
humidity":100,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"clouds":{"all":88},"wind":{"speed":4.76,"deg":336.502},"rain":{},"snow
":{},"sys":{"pod":"n"},"dt_txt":"2016-12-19 03:00:00"},{"dt":1482127200,"main":{"temp":273.785,"temp_min":273.785,"temp_max":273.785,"pressure":1039.01,"sea_level":1042.67,"grnd_leve
l":1039.01,"humidity":100,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"clouds":{"all":92},"wind":{"speed":4.26,"deg":346},"rain":
{},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-19 06:00:00"},{"dt":1482138000,"main":{"temp":272.258,"temp_min":272.258,"temp_max":272.258,"pressure":1042.25,"sea_level":1045.8,"gr
nd_level":1042.25,"humidity":100,"temp_kf":0},"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03n"}],"clouds":{"all":32},"wind":{"speed":4.37,"deg":358.
004},"rain":{},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-19 09:00:00"},{"dt":1482148800,"main":{"temp":269.614,"temp_min":269.614,"temp_max":269.614,"pressure":1045.21,"sea_level
":1048.91,"grnd_level":1045.21,"humidity":100,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],"clouds":{"all":0},"wind":{"speed":4.65,"deg":
6.50052},"rain":{},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-19 12:00:00"},{"dt":1482159600,"main":{"temp":269.846,"temp_min":269.846,"temp_max":269.846,"pressure":1047.99,"sea_l
evel":1051.52,"grnd_level":1047.99,"humidity":100,"temp_kf":0},"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"clouds":{"all":24},"wind":{"speed":3.82
,"deg":15.0016},"rain":{},"snow":{},"sys":{"pod":"d"},"dt_txt":"2016-12-19 15:00:00"},{"dt":1482170400,"main":{"temp":271.084,"temp_min":271.084,"temp_max":271.084,"pressure":1047.12
,"sea_level":1050.67,"grnd_level":1047.12,"humidity":100,"temp_kf":0},"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"clouds":{"all":12},"wind":{"spee
d":3.01,"deg":6.5007},"rain":{},"snow":{},"sys":{"pod":"d"},"dt_txt":"2016-12-19 18:00:00"},{"dt":1482181200,"main":{"temp":270.833,"temp_min":270.833,"temp_max":270.833,"pressure":1
047.98,"sea_level":1051.67,"grnd_level":1047.98,"humidity":100,"temp_kf":0},"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"clouds":{"all":24},"wind":
{"speed":2.77,"deg":356.007},"rain":{},"snow":{},"sys":{"pod":"d"},"dt_txt":"2016-12-19 21:00:00"},{"dt":1482192000,"main":{"temp":269.512,"temp_min":269.512,"temp_max":269.512,"pres
sure":1049.59,"sea_level":1053.29,"grnd_level":1049.59,"humidity":100,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],"clouds":{"all":0},"wi
nd":{"speed":3.42,"deg":11.5001},"rain":{},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-20 00:00:00"},{"dt":1482202800,"main":{"temp":268.748,"temp_min":268.748,"temp_max":268.748,"
pressure":1049.66,"sea_level":1053.33,"grnd_level":1049.66,"humidity":100,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],"clouds":{"all":0}
,"wind":{"speed":2.95,"deg":32.0122},"r
12-17 15:26:07.761 10131 10162 D OkHttp  : ain":{},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-20 03:00:00"},{"dt":1482213600,"main":{"temp":268.25,"temp_min":268.25,"temp_max":268
.25,"pressure":1049.55,"sea_level":1053.32,"grnd_level":1049.55,"humidity":100,"temp_kf":0},"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02n"}],"clouds":{"
all":20},"wind":{"speed":2.62,"deg":19.0007},"rain":{},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-20 06:00:00"},{"dt":1482224400,"main":{"temp":268.425,"temp_min":268.425,"temp_ma
x":268.425,"pressure":1049.37,"sea_level":1053.1,"grnd_level":1049.37,"humidity":100,"temp_kf":0},"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03n"}]
,"clouds":{"all":48},"wind":{"speed":2.51,"deg":17.5004},"rain":{},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-20 09:00:00"},{"dt":1482235200,"main":{"temp":267.975,"temp_min":267.
975,"temp_max":267.975,"pressure":1049.69,"sea_level":1053.44,"grnd_level":1049.69,"humidity":100,"temp_kf":0},"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":
"02n"}],"clouds":{"all":24},"wind":{"speed":2.45,"deg":16.502},"rain":{},"snow":{},"sys":{"pod":"n"},"dt_txt":"2016-12-20 12:00:00"},{"dt":1482246000,"main":{"temp":271.103,"temp_min
":271.103,"temp_max":271.103,"pressure":1049.89,"sea_level":1053.52,"grnd_level":1049.89,"humidity":100,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","ic
on":"02d"}],"clouds":{"all":8},"wind":{"speed":1.88,"deg":26.5005},"rain":{},"snow":{},"sys":{"pod":"d"},"dt_txt":"2016-12-20 15:00:00"},{"dt":1482256800,"main":{"temp":273.519,"temp
_min":273.519,"temp_max":273.519,"pressure":1046.98,"sea_level":1050.59,"grnd_level":1046.98,"humidity":99,"temp_kf":0},"weather":[{"id":803,"main":"Clouds","description":"broken clo
uds","icon":"04d"}],"clouds":{"all":56},"wind":{"speed":1.61,"deg":23},"rain":{},"snow":{},"sys":{"pod":"d"},"dt_txt":"2016-12-20 18:00:00"},{"dt":1482267600,"main":{"temp":273.41,"t
emp_min":273.41,"temp_max":273.41,"pressure":1045,"sea_level":1048.55,"grnd_level":1045,"humidity":97,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds
","icon":"04d"}],"clouds":{"all":88},"wind":{"speed":1.21,"deg":355.501},"rain":{},"snow":{},"sys":{"pod":"d"},"dt_txt":"2016-12-20 21:00:00"}]}
12-17 15:26:07.761 10131 10162 D OkHttp  : <-- END HTTP (10285-byte body)
12-17 15:26:07.807 10131 10131 D AndroidRuntime: Shutting down VM
12-17 15:26:07.807 10131 10131 E AndroidRuntime: FATAL EXCEPTION: main
12-17 15:26:07.807 10131 10131 E AndroidRuntime: Process: org.asteroidos.sync, PID: 10131
12-17 15:26:07.807 10131 10131 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=27; index=27
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at org.asteroidos.sync.ble.WeatherService$2.success(WeatherService.java:84)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at github.vatsal.easyweather.WeatherMap$3.onResponseWeatherObject(WeatherMap.java:141)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at github.vatsal.easyweather.WeatherMap$3.onResponseWeatherObject(WeatherMap.java:122)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at github.vatsal.easyweather.retrofit.api.WeatherRetrofitCallback.onResponse(WeatherRetrofitCallback.java:33)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6126)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-17 15:26:07.807 10131 10131 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-17 15:26:07.809  1073  2801 W ActivityManager:   Force finishing activity org.asteroidos.sync/.DeviceDetailActivity
```

This crash does not occur when I disallow AsteroidOS internet access through AFWall+.

**Comment by TheLastProject** [comment]
I no longer have this issue. I suppose OpenWeatherMap gave data formatted differently than expected. In these scenarios it probably should just not update weather data instead of crash, so I'm leaving this issue open
